classes/console/console.gd
- Optimized warp command for tutorial_1, Now the command goes as follows:
`w tutorial_1 <number from 1 to 4 here>`
- I also added castle lobby warp
`w castle_lobby`
- I made this to make myself feel useful and to possibly help out and learn a bit of coding.
EDIT: this is not more optimized just better maintainable, my bad!
=> Warp command refactor

classes/console/console.gd
=> Optimized if-file-exists check on warp command

classes/player/player.gd
Updates Triple Jump animation to look a bit more centered, and adds a moment at the start where Mario is not in the flip pose so it looks a tad less abrupt.
Also a slight refactor to backflip animation code, because I thought I'd be updating that animation as well, but. Turns out backflips look fine as they are 😕 so I guess it's just a little refactor for consistency.
@GTcreyon @Charpurrr 
N/A
=> Enhance triple jump anim

gui/hud/hud.tscn
Fixes an issue where the FLUDD meter is not visible under any circumstances.
=> Fix fludd meter not being visible

classes/pickup/fludd_box/fludd_pickup_hover.tscn, classes/pickup/fludd_box/fludd_pickup_rocket.tscn, classes/pickup/fludd_box/fludd_pickup_turbo.tscn
Fixed an issue where FLUDD nozzles do not respawn by marking all nozzle drops as non-persistent
Closes #37
=> Fix FLUDD nozzles not respawning

classes/global/singleton/inter_scene_data.gd, classes/global/singleton/singleton.gd, classes/player/fludd_sprite.gd, classes/player/player.gd, classes/player/player.tscn, classes/zone/safety_net/safety_net.gd
Moves FLUDD sprite management out of the player.gd script and into its own script. Includes a fix to behavior when Mario's back is visible (#23)
Closes #23
=> Update handling of FLUDD visuals

classes/entity/enemy/bobomb/bobomb.gd, classes/entity/enemy/bobomb/bobomb.tscn
Adds a red flashing effect to bobombs while they prepare to explode.
Closes #53
=> Bob-omb red flash

classes/player/player.tscn, gui/dialog/dialog_box.gd, gui/dialog/dialog_box.tscn
=> Fix dialog box not showing on large windows

classes/console/console.gd, project.godot
Added an alternate button for slash and runs it through a condition to check if the console if visible or not.
Closes #72
=> fix slash closing the console

classes/pickup/fludd_box/fludd_box.tscn, classes/player/player.gd
Fixes various bugs related to ground pound landing.
Closes #36 (I hope!)
Closes #105
=> Groundpound Landing Fix

classes/interactable/interactable_dialog.gd, classes/interactable/sign/sign.gd, classes/player/player.gd
- Fixed spinning and fludd when interacting with signs and toads
- Moves sign/toad's state check to the InteractableDialog class for more consistency in dialog activation
Closes #115 
Closes #59 
~~#105~~ (Will be moved to a separate pull request)
=> InteractableDialog Bugfixes

classes/player/player.gd
Somehow some residue code from when I was debugging #122 made it into #120.
Time to fix my own bug. -_-
Closes #131
=> Fixed crouching fludd

classes/entity/enemy/cheep_cheep/cheep_cheep.gd, classes/entity/enemy/entity_enemy.gd
Fixes enemies being unable to hurt the player when invincibility runs out. No more standing in fishes!
Closes #38
=> Add continuous collision detection to enemies

classes/interactable/npc/toad/toad.tscn
Updates Toad's collision mask to be consistent with sign.tscn.
Closes #129.
=> Fix Toad Collision Masks

gui/dialog/dialog_box.gd, gui/dialog/dialog_box.tscn
Fixes an issue where the portraits in dialogue boxes doesn't show properly.
=> Fix dialogue box portrait not showing up

classes/player/player.gd, classes/solid/log/log_fall.gd, classes/solid/log/log_fall.tscn
As far as I know, there is never a case where the player needs to be registered as "grounded" when entering the water, so this simple one-line fix hopefully won't cause any problems in the future.
Closes #104
=> Fix underwater log riding

classes/player/character_sprite.gd, classes/player/player.gd
Fixes an issue where buffered jumps would not play the proper jump animation.
=> Fix broken animation when buffering a jump

classes/player/character_sprite.gd, project.godot
Fixes an issue where walking on the seabed would only use the neutral walk animation rather than the loop.
=> Fix broken walking animation on seabed

classes/solid/terrain/pencil.gd, classes/solid/terrain/terrain_polygon.gd, scenes/levels/tutorial_1/tutorial_1_1.tscn
Adds an exported dictionary to manually set the edge type of terrain polygons.
=> Add manual polygon edge type setting

classes/global/singleton/singleton.gd, classes/player/player.gd
Makes sure quitting to title resets all necessary game state.
Fixes #156 and fixes #155.
=> Fix quit-to-title bugs

classes/player/character_sprite.gd, classes/player/player.gd
Fixes an issue where jumping while in coyote time would only play the wall anim, not the jump anim.
=> Fix jumping during coyote time playing fall anim

scenes/levels/tutorial_1/tutorial_1_2.tscn, scenes/levels/tutorial_1/tutorial_1_3.tscn
Adds in the missing terrain edge overrides in t1r2 and t1r3.
=> Fix underwater terrain edges

classes/player/player.tscn
Doubles the speed of the initial dive animation to 10FPS instead of 5FPS.
=> Change speed of initial dive animation

gui/hud/pause_content.gd, gui/pause/pause_menu.tscn
Fixes buggy UI conversion, the UI now looks the same way it does as in Godot 3.5
Closes #192
=> Fix pause menu

scenes/menus/title/logo/logo.gd, scenes/menus/title/space.gd, scenes/menus/title/start_text.gd, scenes/menus/title/title.gd, scenes/menus/title/title_bg/magmoon.gd, scenes/menus/title/title_bg/mushmoon.gd, scenes/menus/title/title_bg/planet.gd
Fixes a few issues causing elements of the title screen not to scale correctly.
=> Fix scaling on title screen

classes/solid/terrain/terrain_border.gd
Frees terrain children nodes from memory instead of just removing them.
Closes #212.
=> Fix terrain memory leak

classes/global/singleton/singleton.gd, classes/player/player.tscn, gui/hud/hud.gd, gui/pause/level_info/level_info.tscn
Fixes screen scaling to match 3.5 branch.
Closes #202 
Closes #201
=> Screen Scaling Fixes

scenes/menus/feedback/feedback.gd
Fixes the feedback menu screenshot not working (crashes the game on some platforms)
=> Fix feedback image

classes/solid/fungus_platform/fungus_stem.tscn
Force fungus stems to repeat their textures.
Closes #206.
=> Fix fungus stem tiling

scenes/menus/feedback/feedback.tscn
Fixes alignment of text on the feedback menu
=> Fix alignment of text on the feedback menu

classes/interactable/npc/toad/toad.gd, gui/dialog/dialog_box.gd
- ~~Add the ability to update toad's color palette in-editor.~~ (Moved to a different PR)
- Refactored how dialog tags are handled
- Fixed dialog text issues
- Fixed dialog portrait issues
Closes #216 
Closes #217
=> Fix dialog

classes/interactable/npc/toad/toad.gd, classes/interactable/npc/toad/toad.tscn
Enables a live preview of toad's color palette in the editor.
=> Update Toad.gd to allow for easier editing

scenes/levels/tutorial_1/tutorial_1_2.tscn, scenes/levels/tutorial_1/tutorial_1_3.tscn, scenes/levels/tutorial_1/tutorial_1_4.tscn
Fixes terrain z-order and hierarchy ordering.
Closes #233
=> Fix terrain z-ordering

gui/water_meter/water_meter.gd, gui/water_meter/water_meter.tscn
Fixes #246 by enabling local coordinates (and removing code that manually resizes them because it's no longer needed).
=> Fix water meter bubbles not moving with meter

classes/entity/enemy/koopa/koopa.tscn, classes/entity/enemy/koopa/parakoopa.gd
Fixed the parakoopas being broken.
Literally all I did was remove one tab from two lines lmao.
Closes #265
=> Fix flying koopas are broken

classes/console/console.gd
Clears the input line after command has been processed
Closes #264
=> Fixed console not clearing

gui/pause/options/touch_menu.tscn, gui/pause/pause_menu.tscn, gui/pause/unpause.gd, scenes/menus/title/main_menu/main_menu.tscn
Fix an issue where the tappable back buttons on some menus scale poorly
=> Fix back button scaling

project.godot
Re-enables translation, which was broken at some point.
=> Enable translation

project.godot
Update the project to Godot 4.2.
This shouldn't be a breaking change, unlike the 3.5->4.0 upgrade, but it's still helpful to do these things as Formal Changes so everyone knows and can rely on This Being What We're Doing Now.
Idk, I hit on some interfaces that are really inconvenient in 4.1 but trivial in 4.2. And I know creyon's already done this to the player refactor, so.
=> Formally update project to Godot 4.2
