GTcreyon/SM63Redux

scenes/menus/feedback/tickbox.gd

Previously pressing F1 on the main menu and trying to check boxes would result in nothing happening, and an error in the Godot debugger:
```
E 0:00:05.915   emit_signal: Error calling method from signal 'pressed': 'Control(tickbox.gd)::_on_Button_pressed': Method not found..
<C++ Source>  core/object.cpp:1242 @ emit_signal()
```
Renaming `res://scenes/menus/feedback/tickbox.gd#_on_Tickbox_pressed` to `_on_Button_pressed` fixes the error message and makes checking the box behave as expected.
(Is this the correct fix? I don't know enough Godot to be sure.)

Fix checking boxes in F1 bug report screen

---

scenes/menus/title/main_menu/main_menu.gd

Previously, main menu text would show diagonal seams on some GPUs and window sizes. This occurred when menu text was positioned at a half-pixel horizontal/vertical offset, causing pixel boundaries to lie in the middle of screen pixels.
The new code rounds menu item positions to integer pixel coordinates. Along with 228f1c9 (which places menu text at integer coordinates relative to menu items), this fixes diagonal seams on main menu text.
It also generalizes better to more than 4 menu items.
Any issues I missed?

Rewrite main menu positioning system, round text to integer pixels

---

classes/interactable/pipe/exit_pipe.gd
classes/interactable/pipe/pipe.gd
classes/interactable/pipe/pipe.tscn

Previously, when Mario entered a warp pipe, the slide-down animation would get interrupted midway by the following error:
```
Invalid get index 'state' (on base: 'Nil').
```
The game would then softlock with Mario still in the pipe.
This bug occurred because Mario, when sliding, would exit the Area2D responsible for checking if he's on top of the pipe. When Mario exits this area, the pipe nulls its reference to him--but this was happening while he was still in the pipe, making it impossible for the pipe to finish sliding him.
To fix this, the code was altered not to null Mario's reference if he's sliding down the pipe when he leaves the Area2D, and the Area2D itself was extended downwards so Mario doesn't leave it during the slide.

Fix and improve on warp pipes

---

classes/interactable/interactable_dialog.gd
classes/player/player.gd

When Mario interacts with a sign (or presumably a Toad), he shifts over to a designated spot relative to the sign (or Toad).
Vexxter on Discord discovered that when signs are children of other nodes, the parent nodes' positions are not taken into account when Mario shifts like this.
This means that if you load in a scene then move its root node, reading a sign in that scene will teleport Mario somewhere crazy (specifically to the global position with the same coordinates as the sign's local position).
Using the interactable's global position takes parent nodes into account, thereby solving the problem.
Just to be on the safe side, also made sure Mario uses global coordinates for this shift animation. He's a child of the scene root, and the scene root is no more guaranteed to be at (0,0) …

Use interactables' global position when Mario slides up to them

---

scenes/menus/level_designer/selection_handler.gd

Currently, the "edit polygon" button incorrectly shows for all objects in the level designer, not just polygon objects:
Looks like code to fix this was almost finished; this just pushes it the last little bit of the way there.

Properly hide polygon-edit button in level designer

---

classes/interactable/door/door.gd
classes/interactable/door/door.tscn
classes/interactable/door/door_skin.gd
classes/interactable/door/double_door.tscn
classes/interactable/door/double_doors.gd
classes/interactable/door/skins/castle_door_diamond.tres
classes/interactable/interactable_exit.gd
classes/interactable/interactable_warp.gd
classes/interactable/pipe/pipe.gd
project.godot

Did some work to nicen up doors and make them consistent with the rest of the project:
- For starters, doors now do scene changes with WindowWarp like pipes do, rather than directly calling `get_tree().change_scene_to(next_scene)`. 
- Moved doors' origins to bottom center to facilitate snapping to the ground.
- Doors now render at Z = -1, behind Mario by default, like signs do.
- Improved the enter-door animation somewhat. The doorframe now stays in place as it should, and Mario now moves over and looks in as the door opens. This is definitely a work-in-progress, waiting on an enter-door animation for Mario, but it's a decent placeholder for now.
- Added ability to switch doors' sprites at runtime.
- Made a dedicated class for double doors. Double doors are internally two normal doors …

Update and improve doors

---

.gitignore

On occasion, I like to use Visual Studio Code (VSCode) to write and edit GDScript. When VSCode loads a project root folder, it auto-generates a `.vscode` folder in the root folder. Its contents absolutely should not be versioned because they are highly user-specific, and basically irrelevant to the project at large.

Ignore auto-generated .vscode folder

---

classes/pickup/fludd_box/fludd_box.tscn

FLUDD box opening was painfully loud by default. Dropped the volume a bit.

Quieter FLUDD box

---

CONTRIBUTING.md

Adds branch naming conventions to the style guide. These were discussed on the Discord server, and it seems wise to lock them in for our own ease of reference (as well as outsiders').
I took the liberty of adding the `repo-___` category for changes to the repository itself (like this one!), since this definitely won't be the last time anybody needs to update the style guide :)
@GTcreyon @jaschutte 
N/A

Canonize branch naming conventions

---

classes/solid/log/log_fall.gd

Logs now have a customizable lifetime, set with an export variable. They will fall until they reach a max speed (such that Mario doesn't fall off), and fade out when the timer runs out.

Customizable lifetime for falling logs

---

classes/pickup/bottle/bottle_big.tscn
classes/pickup/bottle/bottle_small.tscn

Water bottles were set as persistent, for some reason. Now they're not.
@GTcreyon 
Closes #77

Fix water bottles not reloading with room

---

classes/pickup/fludd_box/fludd_box.gd
classes/pickup/fludd_box/fludd_pickup.gd

#82 missed a couple spots when it renamed the FLUDD nozzle enum. Fixing those real quick.
@GTcreyon 
@jaschutte 
N/A

Two renames of Singleton.n got missed

---

classes/player/player.gd

Adjusts hover spray offset to visually match the position of the nozzle.
This was done by a simple change to the particle system's hard-coded position offset, as well as some refactoring to make the offset easier to tune. The spray plume effect was also being placed using this offset, and it looked fine already, so I had to give it its own offset value to keep it where it already was.
While testing, I discovered that not only did the spray effect have a different offset when diving, but that said offset didn't even change with the player's rotation. By making the offset rotate appropriately, I was able to completely remove the dive offset and rely on the normal offset value for everything, and end up with spray consistently coming from the nozzle no matter what angle Mario is currently …

Align hover spray to nozzle

---

classes/misc/residual_sfx/residual_sfx.gd
classes/pickup/bottle/bottle_big.tscn
classes/pickup/bottle/bottle_small.tscn
classes/pickup/coin/blue/coin_blue.tscn
classes/pickup/coin/red/coin_red.tscn
classes/pickup/coin/yellow/coin_yellow.tscn
classes/pickup/fludd_box/fludd_pickup_hover.tscn
classes/pickup/fludd_box/fludd_pickup_rocket.tscn
classes/pickup/fludd_box/fludd_pickup_turbo.tscn
classes/pickup/pickup.gd

Adds sound support directly to the pickup base class, so it can be shared between all pickups with zero effort.
The design is similar to #85, just a whole lot simpler (only one sound hook instead of three).
@GTcreyon @jaschutte
Important step towards #35.

Add sound infrastructure to pickup baseclass

---

classes/pickup/bottle/bottle.gd
classes/pickup/bottle/bottle_big.tscn
classes/pickup/bottle/bottle_small.tscn
classes/pickup/pickup.gd

Makes bottles respawn 30 seconds after being collected.
The respawn functionality was added to the `Pickup` class, since powerup stars (wing/metal/vanish) also need to respawn after collection.
@GTcreyon @jaschutte 
Closes #78

Respawn bottles on a timer

---

classes/pickup/pickup.gd

Attach residual SFX to scene root instead of item's parent (or parent's parent), just to make sure it's as safe as possible.
Amends #89

Light refinement to item sound infrastructure

---

.gitignore

Add `desktop.ini` to the .gitignore.
For context, `desktop.ini` files are auto-generated by Windows Explorer to control the way folders are shown. That seems kind of personal, not to mention completely irrelevant to Mac+Linux users.
N/A

Don't version desktop.ini files

---

classes/player/player.gd
classes/player/player.tscn

Corrects the position of the player's feet area during a dive state to ensure they properly trigger collisions.
Closes #102

Fix position of player's feet during dive state

---

classes/global/singleton/singleton.gd
gui/timer/timer.gd
project.godot

Adds a bind option for Show Timer. Also unbinds Reset Run by default.
This allows speedrunners to bind these manually, while not interfering with casual players.
Closes #100

Allow Show Timer button to be bound

---

classes/pickup/pickup.gd

Changed the Pickup class to contain a has_node() check in the _pickup_sound() method, and a check to ensure the object would not respawn before reparenting the AudioPlayer.
Closes #113

Fixed pickup crash bug

---

classes/entity/enemy/koopa/parakoopa.gd

Fixes a memory leak found in paratroopa.gd, where orphan nodes weren't being freed.
Closes #123

Fix Paratroopa memory leak

---

classes/entity/enemy/koopa/koopa.gd
classes/misc/residual_sfx/residual_sfx.gd

Upgrades `ResidualSFX.new_from_existing` to handle more errors, better.
In particular, it now does the following:
- Crashes if the node it was given is not an audio source. (This can be downgraded to an error if needed.)
- Prints an error if the node it was given is an `AudioStreamPlayer3D`. Since the game is 2D, these probably shouldn't be in use anyway.
- Prints an error if the destroy-on-finished-playing signal is connected twice. This situation already errors, but handling it manually lets us give more specific information: what exactly is going wrong, what's been known to cause this before, where to check to try and fix it.
Was supposed to deal with #130. It didn't, but it should still be helpful in fixing that bug.

Upgrade ResidualSFX.new_from_existing error handling

---

classes/entity/enemy/koopa/koopa.gd

Checks if Koopas have already been struck before allowing a shell to spawn.
Closes #130.

Fix Koopas spawning multiple shells when being struck

---

classes/entity/enemy/koopa/parakoopa.gd

Change parakoopa.gd's damage.monitoring assignment to be deferred since Godot doesn't like it when you change an area's monitoring status in a signal.
Closes #127.

Fix lingering hitbox in Parakoopa

---

classes/pickup/fludd_box/fludd_box.tscn

Changes the Z-index of the FLUDD box to layer it behind the player instead of in front.

Layer FLUDD box behind the player

---

scenes/menus/title/main_menu/main_menu.tscn

Removes desaturation shader from Extras arrow on the main menu, as it is no longer needed due to the addition of the lock symbol.

Remove desaturation shader from Extras arrow

---

scenes/menus/feedback/feedback.gd

Previously, the quote block for the Description section in the feedback menu would only quote the first line. This fixes that, allowing all lines to be included in the quote block.

Fix broken quote blocks in feedback menu

---

scenes/menus/feedback/feedback.gd

Appends a truncated SHA-1 hash to feedback reports, so they can be referenced more easily.
This is marked as draft, because I'm not sure the `%` sign is the best symbol to use.
Closes #151

Append a hash to feedback reports

---

classes/player/fludd_sprite.gd
classes/player/player.gd

When switching FLUDD nozzles mid-spray, the spray sounds would continue, at least when in air. The spray sound now ends appropriately.
Switching mid-spray while diving was not tested, but a code inspection suggests the same issue was present, so the issue was also fixed there.
Fixes a bug reported by Vexxter in the #playtesting channel.

End FLUDD sound when switching off hover nozzle

---

classes/player/player.gd
gui/theme_gui.tres
project.godot

For some reason, sfx.stop() doesn't work when used on the same frame as sfx.play(). Setting stream_paused doesn't seem to have any issues though, so this fix makes spin_sfx use that instead. 
Closes #101

Fix spin sound not stopping properly

---

classes/misc/residual_sfx/residual_sfx.gd

Fixes an issue where ResidualSFXes created through `ResidualSFX.new()` would not be on the SFX bus, and as such would not be muted by Mute SFX.

Fix bus of ResidualSFX

---

classes/pickup/fludd_box/fludd_pickup_hover.tscn
classes/pickup/fludd_box/fludd_pickup_rocket.tscn
classes/pickup/fludd_box/fludd_pickup_turbo.tscn

Fixes an issue where FLUDD nozzle pickups would layer in front of the boxes they drop from, resulting in a flawed animation.

Fix nozzle pickups layering in front of boxes

---

classes/interactable/interactable_dialog.gd
classes/player/character_sprite.gd
gui/dialog/dialog_box.gd

Fixes an issue where reading a sign while spinning would cause the neutral animation to play instead.

Fix animation not being set properly when reading signs

---

classes/global/singleton/singleton.gd
classes/misc/twirl_heart/twirl_heart.gd
classes/player/player.gd

I added a `reset_bus_effect` function to the Singleton class, it resets a chosen bus effect in an audio bus. Additionally, I added a call to this function whenever the player is loaded. This is so any left over reverb is automatically cleared when you enter a new scene, preventing leftover garbage reverb from playing. I also fixed a minor typo.
Closes #168

Fix reverb carrying over between scenes

---

CONTRIBUTING.md

Since we're not yet on the 4.0 branch, updates the link to the Godot style guide to explicitly point to version 3.5. Hopefully we remember to update this when we eventually switch to 4.1
N/A

Update style guide docs reference while we're not on 4.x

---

classes/solid/terrain/terrain_border.gd
classes/solid/terrain/terrain_border_endcaps.gd
classes/solid/terrain/terrain_polygon.gd
classes/solid/terrain/terrain_polygon.tscn

Modifies terrain system to support background terrain layers.
***NOTE:** This PR is branched from #181. New changes start on May 30th.*
To make background terrain, two features are required: disable-able collision, and changeable Z-order. Collision was dead simple to connect to a checkbox, so the bulk of the changes here went into Z-sorting.
See, the system was designed to render the top border, then bottom, then sides, and use Z-sorting to put them at the right depth relative to each other. The problem was, this meant a terrain object was on no less than three Z-layers (body, sides, top+bottom). If you wanted to put a terrain in the background, it had to move no fewer than 3 steps at a time in order to stay together--which seems both inconvenient and counterintuitive!
With that in mind, …

Background terrain support

---

classes/global/singleton/singleton.gd
classes/player/player.gd

I've caught #168 cropping up here and there still--it's a lot subtler, but on rare occasions, enough can happen immediately before jumping out of water that the leftover reverb tail is audible when it spills over into the next body of water (try superswimming out of water immediately after pounding into it).
To fix this, I moved the reverb reset from `_ready()` to `_on_WaterCheck_area_entered()`. This way, the reverb buffer is forcibly cleared every single time Mario hits water, meaning there's no possible way reverb from last time could spill over.
Closes some loose ends on #168.

Fix garbage reverb thoroughly

---

scenes/menus/level_designer/icons/enemy/cheep_cheep.tres
scenes/menus/level_designer/icons/pickup/coin_blue.tres
scenes/menus/level_designer/icons/pickup/coin_red.tres
scenes/menus/level_designer/icons/pickup/coin_yellow.tres
scenes/menus/level_designer/icons/pickup/silver_shine.tres
scenes/menus/level_designer/items.xml.tres
scenes/menus/level_designer/menu_control.gd

Apparently ever since the 0.1.6 graphics overhaul, opening the Level Designer has crashed the game (editor)/caused catastrophic breakage (web). This PR fixes that.
The problem was, the LD was using loose frames of animation as icons for the item menu. When the loose frames were replaced with atlases, the paths to the loose frames weren't updated--nor could they be, since the frames were now part of large atlases.
To fix this, I cut Atlas Textures (quicker to make than PNGs) of all the offending objects--coins in all colors, Cheep Cheeps, and Silver Shines (which currently use a HUD widget for their icon)--and updated the icon loader to support `.tres` Texture resources in addition to .png files. (Any Texture, not just Atlas Textures--seems silly to limit ourselves :P)
N/A - just hard to …

Make LD load again by cutting new item icons

---

classes/water/water.gd

Fixes an issue with the waves being too big in 4.1
I tried finding a proper fix for this, but I can't see why it suddenly amplifies the effect.
This works however, and the scaling doesn't seem to be impacted is this should suffice.
Closes N/A

Fixed water splashes being huge

---

classes/water/water_viewport.gdshader

Fixes an issue where the water animation was frozen at the first frame of the animation.
It also removed an if statement which was unneeded and filled in transparent pixels -which should remain transparent-.
Closes #198

Fixed texture not animating & removed unneeded outline addition

---

scenes/menus/title/main_menu/main_menu.tscn

The descriptions on the main menu had misconfigured control alignments. This fixes that.

Fix main menu item description misalignment

---

classes/entity/passive/goonie/goonie.gd
classes/global/singleton/warp.gd
classes/global/touch_control/touch_button.gd
classes/global/touch_control/touch_controls.gd
classes/player/character_sprite.gd
classes/solid/telescoping/tipping_log/tipping_log.gd
classes/water/water.gd
gui/hud/shine_map.gd
gui/pause/map_course.gd
gui/pause/unpause.gd
scenes/levels/tutorial_1/bg/clouds_lower.gd
scenes/menus/title/logo/logo.gd
scenes/menus/title/start_text.gd
scenes/menus/title/title.gd
scenes/menus/title/title_bg/mushmoon.gd

Fix all remaining spots which give int-division warnings.
Spots commented with `# warning-ignore:integer_division` were upgraded to use the proper Godot 4 version of that command (`@warning_ignore("integer_division")`).
I'm assuming other erroring divisions were expected to divide as float, so any such spots have been upgraded with the required casts to make that happen.
A lot of these warnings came from spots that were using `get_window().size`. Many of them called this function multiple times per function, or even per line, and that seems a bit stinky...so I rewrote them to call once, convert to a float vector, then reuse the converted vector. Also saves horizontal real estate in the scripts.

Fix all spots which give int division warnings

---

classes/entity/enemy/entity_enemy.gd
classes/entity/enemy/koopa/parakoopa.gd
classes/entity/enemy/koopa/parakoopa.tscn
classes/entity/entity.gd

Actual changes:
- Enemy entities use a new "deferred" connect mode to ensure their signals are always processed after the player.
- While fixing the parakoopa's hitboxes, I also refactored its script a bit.
Some extra things to note:
- While spinning enemies is more consistent, the timing feels way too generous now. Will open a proposal to fix this later.
- The transitions between parakoopas, koopas and shells are still super jank. Will open a proposal to clean them up later.
Closes #128
Fixes the first reproduction scenario of #118

Fix enemy hitbox priorities

---

scenes/menus/title/main_menu/main_menu.tscn

Makes all textures inside the main menu repeat by default. This fixes the diagonal shines on the buttons, as well as the tiling on the apparently unused Line2D called "Stripe."
While I'm at it, also renames the diagonal shines to match their script name (which is "sheen," not "shine"--much clearer in a game about shines).
Closes #225, both parts of it.

Fix main menu texture repeats

---

classes/interactable/interactable_dialog.gd
classes/zone/camera_area/camera_area.gd
classes/zone/trigger/warpzone/warp_zone.gd

In the editor, a number of toolscripts throw errors on scene load, due to trying to `@onready` get nodes that don't exist yet. This PR fixes that using null checks, later initialization, and in `camera_area`'s case, just un-toolscripting things that don't need it.
N/A

Fix editor errors caused by toolscripts

---

gui/life_meter/life_meter.tscn

Very simple fix that prevents the life hud's coin meter from flashing when changing scenes.

Fix life hud flashing

---

classes/entity/enemy/cheep_cheep/cheep_cheep.tscn

Sets Cheep Cheeps' transition animations to not loop. Animations fire different signals when they loop versus when they end, and because the code is wired to the end signal, it was never advancing to the loop portion....
Closes #238.

Fix Cheep Cheep animations

---

gui/water_meter/water_meter.gd
gui/water_meter/water_meter.tscn

Manually syncs the bubble systems' particle scale with the HUD's root.
All three water particle systems share a process material, so the script only needs to get it from one of them.
Also, code refactor and cleanup, like usual.
Closes #237.
@sbritorodr also submitted a fix; see #242.

Fix water meter bubbles scaling with window

---

classes/player/camera.gd
classes/player/player.tscn
shaders/distance_field.gdshader
shaders/distance_field.tres

Readjusts the FLUDD spray particle system to look close to 3.1 FLUDD spray. (It's not exact, for reasons me and @jaschutte couldn't quite pin down, but it's close enough.)
Exact changes include:
- Readjusting particle gravity/velocity ranges (1.5 times original) and sizes.
- Giving particle's shader an adjustable cutoff value, to adjust the "blobbiness" of spray particles.
- Adjusting said blobbiness. Particles were a little bit thinner than the 3.5 versions.
Closes #195.

Fix tiny FLUDD spray

---

classes/interactable/pipe/pipe.tscn

Somewhere along the line, pipes were set to no longer monitor the player's layer. This PR simply fixes that, allowing pipes to work again.
N/A

Make pipes usable again

---

classes/player/fludd_spray_renderer.gd

Fixes an issue causing FLUDD bubbles to be cut off when the window is resized. Changed to using the specific window size rather than canvas size, since this seems closer to the original intention.
Closes #229

Fix FLUDD bubbles cutting off

---

classes/solid/telescoping/tipping_log/tipping_log.gd

Fixes jittering collision on tipping logs by forcing the player to snap to the floor.
Closes #248

Fix tipping log jitter

---

classes/player/character_sprite.gd
classes/player/player.gd

~~Removes the wind-up from character_sprite.gd (If we really want this effect, it should be implemented by actually moving the character instead of just the sprite, so physics can remain consistent)~~
Fixes the order of processing ground pound inputs. SIRIUS: This makes ground pounds work correctly on moving platforms.
Closes #179

Fix ground pounding moving platforms

---

gui/hud/level_info.gd
scenes/menus/level_designer/ldui/themes/ld_theme.tres
scenes/menus/visual_pipescript/node.gd
scenes/menus/visual_pipescript/node_placer.gd

As of #253, `bylight.tres` has been removed as redundant (in favor of `bylight.otf`), but was still referenced by some scripts (and the LD theme I guess). Fix those references to point to the still-existing file.
Cleans up a hasty review process on #253.

Fix leftover references to bylight.tres

---

classes/player/character_sprite.gd
classes/player/player.gd

The pound spin animation appears to lift the player up slightly before the drop. This PR makes it so that this lifting isn't just visual, but rather actually affects the player's position.
This does have the side effect of giving the player a new movement option. Players likely assumed they already had this option, so this probably isn't a huge change to the play experience. Nonetheless, it deserves a mention.
Shout out to @Kuma-Boo for coming up with the apply-to-velocity method in PR #241. It's simple enough that I can't believe I ever considered applying the lift directly to the player position.
Closes #177.

Apply pound windup animation to actual player position

---

classes/entity/enemy/koopa/parakoopa.gd
classes/interactable/npc/toad/toad.gd
scenes/levels/tutorial_1/tutorial_1_3.tscn
scenes/levels/tutorial_1/tutorial_1_4.tscn
shaders/palette.tres

Fix an issue with the palette material causing the UIDs of its duplicates in the scene file to change frequently without designer input.
Closes #255

Fix palette material UIDs regenerating

---

classes/console/console.gd
classes/entity/enemy/koopa/parakoopa.gd
classes/entity/enemy/thwomp/thwomp.gd
classes/interactable/door/door_skin.gd
classes/interactable/interactable_dialog.gd
classes/interactable/npc/toad/toad.gd
classes/solid/moving_platform/pivot.gd
classes/solid/telescoping/telescoping.gd
classes/solid/telescoping/tipping_log/tipping_log.gd
classes/zone/trigger/warpzone/warp_zone.gd

Disable some toolscripts that are no longer relevant, since the scene editor will not be used for future level creation.
This is on the 4.1 branch, because the toolscript syntax changed in 4.1.
I hoped this would resolve #255, but it doesn't.

Disable some toolscripts

---

locale/translations/pt_BR.po

Fixes a malformed BBCode color block, which was appearing as plain text rather than tinting the enclosed text.
Closes #280.

Fix malformed color code in Portuguese translation

---

classes/player/player.gd

Make it so that uncrouching (crouch resetting) is counted as a valid case for allowing a turn around while moving. This prevents the odd behaviour of moving backwards while the uncrouch animation is still playing.
Closes #180

Fix odd behaviour when player moves backwards during the uncrouch animation

---

scenes/levels/tutorial_1/tutorial_1_4.tscn

In Tutorial 1 Room 4, the first rotating block is white translucent. It should be color. This fixes that.

Fix t1r4 color block being white instead of color

---

classes/entity/enemy/koopa/koopa.gd

Possibly fixes a bug where koopas could split into two shells under specific circumstances. (I'm not quite precise enough with timing to repro it myself 😖)
Ticket &70cff suggests that the problem occurs when a stomp and spin both hit the koopa at once. A code review bears this theory out: if both the stomp and strike functions run in the same frame, the spawn-shell-and-delete-self function `into_shell` is called both times.
To fix this, I modified `into_shell` to do nothing if the koopa is queued for deletion (which it always will be after the function is called once). I could easily have modified the call sites instead, but this way there's only one new if statement, not two, and no extra thought is required when using `into_shell` in the future.
Theoretically closes ticket &70cff, and a …

Fix koopa producing two shells if both stomped and struck

---

backgrounds/zooming_parallax_background.gd
classes/player/camera.gd
scenes/levels/tutorial_1/bg/bg_t1.tscn

This has been on the backburner for way too long! Fixes background scaling so that sized-up windows don't show "backstage" parts of the background.
The parallax is not 100% consistent between scaling levels. I'm not sure how to fix this, but it's a very subtle problem that's (currently) easy to miss, so I'll leave it for now. We'll see how new backgrounds adapt to it....
Been reported many times, including by @GTcreyon.

Fix background scaling in sized-up windows

---

classes/interactable/pipe/pipe.gd
classes/interactable/pipe/pipe.tscn

Offset the pipe's sprite and collision a few pixels downward
Pipe would be offset by a few pixels vertically when placed

Pipe offsetting when loading a level in the LD
